<?php

/**
 * PluginfpPaymentTaxToDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfpPaymentTaxToDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginfpPaymentTaxToDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginfpPaymentTaxToData');
    }
}