<?php

/**
 * PluginfpPaymentTaxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    fpPayment
 * @subpackage Tax
 * @author     Ton Sharp <Forma-PRO@66ton99.org.ua>
 */
class PluginfpPaymentTaxTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return PluginfpPaymentTaxTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginfpPaymentTax');
  }
}